# Generated by Django 4.0.4 on 2022-05-04 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localizacao', '0001_initial'),
        ('core', '0005_pontoturistico_endereco_pontoturistico_avaliacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='Endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localizacao.endereco'),
        ),
    ]
